// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <ostream>
#include <string>

namespace file_saver {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const ::flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const ::flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  ::flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class FileSaverHostApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};



// Everything a native save needs. `bytes` or `sourcePath` is set, not both.
//
// Generated class from Pigeon that represents data sent in messages.
class SaveRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit SaveRequest(
    const std::string& name,
    const std::string& file_extension,
    bool include_extension,
    const std::string& mime_type);

  // Constructs an object setting all fields.
  explicit SaveRequest(
    const std::string& name,
    const std::vector<uint8_t>* bytes,
    const std::string* source_path,
    const std::string& file_extension,
    bool include_extension,
    const std::string& mime_type,
    const std::string* initial_directory,
    const std::string* dialog_title,
    const std::string* album);

  const std::string& name() const;
  void set_name(std::string_view value_arg);

  const std::vector<uint8_t>* bytes() const;
  void set_bytes(const std::vector<uint8_t>* value_arg);
  void set_bytes(const std::vector<uint8_t>& value_arg);

  const std::string* source_path() const;
  void set_source_path(const std::string_view* value_arg);
  void set_source_path(std::string_view value_arg);

  const std::string& file_extension() const;
  void set_file_extension(std::string_view value_arg);

  bool include_extension() const;
  void set_include_extension(bool value_arg);

  const std::string& mime_type() const;
  void set_mime_type(std::string_view value_arg);

  const std::string* initial_directory() const;
  void set_initial_directory(const std::string_view* value_arg);
  void set_initial_directory(std::string_view value_arg);

  const std::string* dialog_title() const;
  void set_dialog_title(const std::string_view* value_arg);
  void set_dialog_title(std::string_view value_arg);

  const std::string* album() const;
  void set_album(const std::string_view* value_arg);
  void set_album(std::string_view value_arg);

  bool operator==(const SaveRequest& other) const;
  bool operator!=(const SaveRequest& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const SaveRequest& obj);
 private:
  static SaveRequest FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class FileSaverHostApi;
  friend class PigeonInternalCodecSerializer;
  std::string name_;
  std::optional<std::vector<uint8_t>> bytes_;
  std::optional<std::string> source_path_;
  std::string file_extension_;
  bool include_extension_;
  std::string mime_type_;
  std::optional<std::string> initial_directory_;
  std::optional<std::string> dialog_title_;
  std::optional<std::string> album_;
};


// Generated class from Pigeon that represents data sent in messages.
class DownloadRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit DownloadRequest(const std::string& url);

  // Constructs an object setting all fields.
  explicit DownloadRequest(
    const std::string& url,
    const std::string* name,
    const ::flutter::EncodableMap* headers);

  const std::string& url() const;
  void set_url(std::string_view value_arg);

  const std::string* name() const;
  void set_name(const std::string_view* value_arg);
  void set_name(std::string_view value_arg);

  const ::flutter::EncodableMap* headers() const;
  void set_headers(const ::flutter::EncodableMap* value_arg);
  void set_headers(const ::flutter::EncodableMap& value_arg);

  bool operator==(const DownloadRequest& other) const;
  bool operator!=(const DownloadRequest& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const DownloadRequest& obj);
 private:
  static DownloadRequest FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class FileSaverHostApi;
  friend class PigeonInternalCodecSerializer;
  std::string url_;
  std::optional<std::string> name_;
  std::optional<::flutter::EncodableMap> headers_;
};


class PigeonInternalCodecSerializer : public ::flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const ::flutter::EncodableValue& value,
    ::flutter::ByteStreamWriter* stream) const override;
 protected:
  ::flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader* stream) const override;
};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class FileSaverHostApi {
 public:
  FileSaverHostApi(const FileSaverHostApi&) = delete;
  FileSaverHostApi& operator=(const FileSaverHostApi&) = delete;
  virtual ~FileSaverHostApi() {}
  // Writes to app storage without a dialog. Android only.
  virtual void SaveFile(
    const SaveRequest& request,
    std::function<void(ErrorOr<std::optional<std::string>> reply)> result) = 0;
  // Shows the platform save dialog; null when the user cancels.
  virtual void SaveAs(
    const SaveRequest& request,
    std::function<void(ErrorOr<std::optional<std::string>> reply)> result) = 0;
  // Adds an image or video to the photo library. Android and iOS only.
  virtual void SaveToGallery(
    const SaveRequest& request,
    std::function<void(ErrorOr<std::optional<std::string>> reply)> result) = 0;
  // Hands a URL to the system downloader. Android only.
  virtual ErrorOr<std::string> DownloadLink(const DownloadRequest& request) = 0;

  // The codec used by FileSaverHostApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `FileSaverHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    FileSaverHostApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    FileSaverHostApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  FileSaverHostApi() = default;
};
}  // namespace file_saver
#endif  // PIGEON_MESSAGES_G_H_
