// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <cmath>
#include <limits>
#include <map>
#include <optional>
#include <sstream>
#include <string>

namespace file_saver {
using ::flutter::BasicMessageChannel;
using ::flutter::CustomEncodableValue;
using ::flutter::EncodableList;
using ::flutter::EncodableMap;
using ::flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

namespace {
template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b);

bool PigeonInternalDeepEquals(const double& a, const double& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b);

template<typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b);

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b);

template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b) {
  return a == b;
}

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (size_t i = 0; i < a.size(); ++i) {
    if (!PigeonInternalDeepEquals(a[i], b[i])) {
      return false;
    }
  }
  return true;
}

template <typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (const auto& kv : a) {
    bool found = false;
    for (const auto& b_kv : b) {
      if (PigeonInternalDeepEquals(kv.first, b_kv.first)) {
        if (PigeonInternalDeepEquals(kv.second, b_kv.second)) {
          found = true;
          break;
        } else {
          return false;
        }
      }
    }
    if (!found) {
      return false;
    }
  }
  return true;
}

bool PigeonInternalDeepEquals(const double& a, const double& b) {
  // Normalize -0.0 to 0.0 and handle NaN equality.
  return (a == b) || (std::isnan(a) && std::isnan(b));
}

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b) {
  if (!a && !b) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b) {
  if (a.get() == b.get()) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b) {
  if (a.index() != b.index()) {
    return false;
  }
  if (const double* da = std::get_if<double>(&a)) {
    return PigeonInternalDeepEquals(*da, std::get<double>(b));
  } else if (const ::flutter::EncodableList* la = std::get_if<::flutter::EncodableList>(&a)) {
    return PigeonInternalDeepEquals(*la, std::get<::flutter::EncodableList>(b));
  } else if (const ::flutter::EncodableMap* ma = std::get_if<::flutter::EncodableMap>(&a)) {
    return PigeonInternalDeepEquals(*ma, std::get<::flutter::EncodableMap>(b));
  }
  return a == b;
}

template <typename T>
size_t PigeonInternalDeepHash(const T& v);

size_t PigeonInternalDeepHash(const double& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v);

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v);

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v);

template <typename T>
size_t PigeonInternalDeepHash(const T& v) {
  return std::hash<T>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v) {
  size_t result = 1;
  for (const auto& item : v) {
    result = result * 31 + PigeonInternalDeepHash(item);
  }
  return result;
}

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v) {
  size_t result = 0;
  for (const auto& kv : v) {
    result += ((PigeonInternalDeepHash(kv.first) * 31) ^ PigeonInternalDeepHash(kv.second));
  }
  return result;
}

size_t PigeonInternalDeepHash(const double& v) {
  if (std::isnan(v)) {
    // Normalize NaN to a consistent hash.
    return std::hash<double>()(std::numeric_limits<double>::quiet_NaN());
  }
  if (v == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return std::hash<double>()(0.0);
  }
  return std::hash<double>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v) {
  size_t result = v.index();
  if (const double* dv = std::get_if<double>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*dv);
  } else if (const ::flutter::EncodableList* lv =
                 std::get_if<::flutter::EncodableList>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*lv);
  } else if (const ::flutter::EncodableMap* mv =
                 std::get_if<::flutter::EncodableMap>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*mv);
  } else {
    std::visit(
        [&result](const auto& val) {
          using T = std::decay_t<decltype(val)>;
          if constexpr (!std::is_same_v<T, double> &&
                        !std::is_same_v<T, ::flutter::EncodableList> &&
                        !std::is_same_v<T, ::flutter::EncodableMap> &&
                        !std::is_same_v<T, std::monostate> &&
                        !std::is_same_v<T, ::flutter::CustomEncodableValue>) {
            result = result * 31 + PigeonInternalDeepHash(val);
          }
        },
        v);
  }
  return result;
}

template <typename T>
std::string PigeonInternalToString(const T& v);

std::string PigeonInternalToString(const bool& v);

template <typename T>
std::string PigeonInternalToString(const std::vector<T>& v);

template <typename K, typename V>
std::string PigeonInternalToString(const std::map<K, V>& v);

template <typename T>
std::string PigeonInternalToString(const std::optional<T>& v);

template <typename T>
std::string PigeonInternalToString(const std::unique_ptr<T>& v);

std::string PigeonInternalToString(const ::flutter::EncodableValue& v);

template <typename T>
std::string PigeonInternalToString(const T& v) {
  std::stringstream ss;
  if constexpr (std::is_enum_v<T>) {
    ss << static_cast<int>(v);
  } else {
    ss << v;
  }
  return ss.str();
}

std::string PigeonInternalToString(const bool& v) {
  return v ? "true" : "false";
}

template <typename T>
std::string PigeonInternalToString(const std::vector<T>& v) {
  std::stringstream ss;
  ss << "[";
  for (size_t i = 0; i < v.size(); ++i) {
    if (i > 0) {
      ss << ", ";
    }
    ss << PigeonInternalToString(v[i]);
  }
  ss << "]";
  return ss.str();
}

template <typename K, typename V>
std::string PigeonInternalToString(const std::map<K, V>& v) {
  std::stringstream ss;
  ss << "{";
  bool first = true;
  for (const auto& kv : v) {
    if (!first) {
      ss << ", ";
    }
    first = false;
    ss << PigeonInternalToString(kv.first) << ": " << PigeonInternalToString(kv.second);
  }
  ss << "}";
  return ss.str();
}

template <typename T>
std::string PigeonInternalToString(const std::optional<T>& v) {
  return v ? PigeonInternalToString(*v) : "null";
}

template <typename T>
std::string PigeonInternalToString(const std::unique_ptr<T>& v) {
  return v ? PigeonInternalToString(*v) : "null";
}

std::string PigeonInternalToString(const ::flutter::EncodableValue& v) {
  return std::visit(
      [](const auto& val) {
        using T = std::decay_t<decltype(val)>;
        if constexpr (std::is_same_v<T, std::monostate>) {
          return std::string("null");
        } else if constexpr (std::is_same_v<T, bool>) {
          return val ? std::string("true") : std::string("false");
        } else if constexpr (std::is_same_v<T, std::string>) {
          return "\"" + val + "\"";
        } else if constexpr (std::is_same_v<T, ::flutter::CustomEncodableValue>) {
          return std::string("[custom]");
        } else {
          return PigeonInternalToString(val);
        }
      },
      v);
}

}  // namespace
// SaveRequest

SaveRequest::SaveRequest(
  const std::string& name,
  const std::string& file_extension,
  bool include_extension,
  const std::string& mime_type)
 : name_(name),
    file_extension_(file_extension),
    include_extension_(include_extension),
    mime_type_(mime_type) {}

SaveRequest::SaveRequest(
  const std::string& name,
  const std::vector<uint8_t>* bytes,
  const std::string* source_path,
  const std::string& file_extension,
  bool include_extension,
  const std::string& mime_type,
  const std::string* initial_directory,
  const std::string* dialog_title,
  const std::string* folder)
 : name_(name),
    bytes_(bytes ? std::optional<std::vector<uint8_t>>(*bytes) : std::nullopt),
    source_path_(source_path ? std::optional<std::string>(*source_path) : std::nullopt),
    file_extension_(file_extension),
    include_extension_(include_extension),
    mime_type_(mime_type),
    initial_directory_(initial_directory ? std::optional<std::string>(*initial_directory) : std::nullopt),
    dialog_title_(dialog_title ? std::optional<std::string>(*dialog_title) : std::nullopt),
    folder_(folder ? std::optional<std::string>(*folder) : std::nullopt) {}

const std::string& SaveRequest::name() const {
  return name_;
}

void SaveRequest::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


const std::vector<uint8_t>* SaveRequest::bytes() const {
  return bytes_ ? &(*bytes_) : nullptr;
}

void SaveRequest::set_bytes(const std::vector<uint8_t>* value_arg) {
  bytes_ = value_arg ? std::optional<std::vector<uint8_t>>(*value_arg) : std::nullopt;
}

void SaveRequest::set_bytes(const std::vector<uint8_t>& value_arg) {
  bytes_ = value_arg;
}


const std::string* SaveRequest::source_path() const {
  return source_path_ ? &(*source_path_) : nullptr;
}

void SaveRequest::set_source_path(const std::string_view* value_arg) {
  source_path_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void SaveRequest::set_source_path(std::string_view value_arg) {
  source_path_ = value_arg;
}


const std::string& SaveRequest::file_extension() const {
  return file_extension_;
}

void SaveRequest::set_file_extension(std::string_view value_arg) {
  file_extension_ = value_arg;
}


bool SaveRequest::include_extension() const {
  return include_extension_;
}

void SaveRequest::set_include_extension(bool value_arg) {
  include_extension_ = value_arg;
}


const std::string& SaveRequest::mime_type() const {
  return mime_type_;
}

void SaveRequest::set_mime_type(std::string_view value_arg) {
  mime_type_ = value_arg;
}


const std::string* SaveRequest::initial_directory() const {
  return initial_directory_ ? &(*initial_directory_) : nullptr;
}

void SaveRequest::set_initial_directory(const std::string_view* value_arg) {
  initial_directory_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void SaveRequest::set_initial_directory(std::string_view value_arg) {
  initial_directory_ = value_arg;
}


const std::string* SaveRequest::dialog_title() const {
  return dialog_title_ ? &(*dialog_title_) : nullptr;
}

void SaveRequest::set_dialog_title(const std::string_view* value_arg) {
  dialog_title_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void SaveRequest::set_dialog_title(std::string_view value_arg) {
  dialog_title_ = value_arg;
}


const std::string* SaveRequest::folder() const {
  return folder_ ? &(*folder_) : nullptr;
}

void SaveRequest::set_folder(const std::string_view* value_arg) {
  folder_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void SaveRequest::set_folder(std::string_view value_arg) {
  folder_ = value_arg;
}


EncodableList SaveRequest::ToEncodableList() const {
  EncodableList list;
  list.reserve(9);
  list.push_back(EncodableValue(name_));
  list.push_back(bytes_ ? EncodableValue(*bytes_) : EncodableValue());
  list.push_back(source_path_ ? EncodableValue(*source_path_) : EncodableValue());
  list.push_back(EncodableValue(file_extension_));
  list.push_back(EncodableValue(include_extension_));
  list.push_back(EncodableValue(mime_type_));
  list.push_back(initial_directory_ ? EncodableValue(*initial_directory_) : EncodableValue());
  list.push_back(dialog_title_ ? EncodableValue(*dialog_title_) : EncodableValue());
  list.push_back(folder_ ? EncodableValue(*folder_) : EncodableValue());
  return list;
}

SaveRequest SaveRequest::FromEncodableList(const EncodableList& list) {
  SaveRequest decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[3]),
    std::get<bool>(list[4]),
    std::get<std::string>(list[5]));
  auto& encodable_bytes = list[1];
  if (!encodable_bytes.IsNull()) {
    decoded.set_bytes(std::get<std::vector<uint8_t>>(encodable_bytes));
  }
  auto& encodable_source_path = list[2];
  if (!encodable_source_path.IsNull()) {
    decoded.set_source_path(std::get<std::string>(encodable_source_path));
  }
  auto& encodable_initial_directory = list[6];
  if (!encodable_initial_directory.IsNull()) {
    decoded.set_initial_directory(std::get<std::string>(encodable_initial_directory));
  }
  auto& encodable_dialog_title = list[7];
  if (!encodable_dialog_title.IsNull()) {
    decoded.set_dialog_title(std::get<std::string>(encodable_dialog_title));
  }
  auto& encodable_folder = list[8];
  if (!encodable_folder.IsNull()) {
    decoded.set_folder(std::get<std::string>(encodable_folder));
  }
  return decoded;
}

bool SaveRequest::operator==(const SaveRequest& other) const {
  return PigeonInternalDeepEquals(name_, other.name_) && PigeonInternalDeepEquals(bytes_, other.bytes_) && PigeonInternalDeepEquals(source_path_, other.source_path_) && PigeonInternalDeepEquals(file_extension_, other.file_extension_) && PigeonInternalDeepEquals(include_extension_, other.include_extension_) && PigeonInternalDeepEquals(mime_type_, other.mime_type_) && PigeonInternalDeepEquals(initial_directory_, other.initial_directory_) && PigeonInternalDeepEquals(dialog_title_, other.dialog_title_) && PigeonInternalDeepEquals(folder_, other.folder_);
}

bool SaveRequest::operator!=(const SaveRequest& other) const {
  return !(*this == other);
}

size_t SaveRequest::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(name_);
  result = result * 31 + PigeonInternalDeepHash(bytes_);
  result = result * 31 + PigeonInternalDeepHash(source_path_);
  result = result * 31 + PigeonInternalDeepHash(file_extension_);
  result = result * 31 + PigeonInternalDeepHash(include_extension_);
  result = result * 31 + PigeonInternalDeepHash(mime_type_);
  result = result * 31 + PigeonInternalDeepHash(initial_directory_);
  result = result * 31 + PigeonInternalDeepHash(dialog_title_);
  result = result * 31 + PigeonInternalDeepHash(folder_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const SaveRequest& obj) {
  os << "SaveRequest(";
  os << "name: ";
  os << PigeonInternalToString(obj.name_);
  os << ", bytes: ";
  if (obj.bytes_) {
    os << PigeonInternalToString(*obj.bytes_);
  }
  else {
    os << "null";
  }
  os << ", source_path: ";
  if (obj.source_path_) {
    os << PigeonInternalToString(*obj.source_path_);
  }
  else {
    os << "null";
  }
  os << ", file_extension: ";
  os << PigeonInternalToString(obj.file_extension_);
  os << ", include_extension: ";
  os << PigeonInternalToString(obj.include_extension_);
  os << ", mime_type: ";
  os << PigeonInternalToString(obj.mime_type_);
  os << ", initial_directory: ";
  if (obj.initial_directory_) {
    os << PigeonInternalToString(*obj.initial_directory_);
  }
  else {
    os << "null";
  }
  os << ", dialog_title: ";
  if (obj.dialog_title_) {
    os << PigeonInternalToString(*obj.dialog_title_);
  }
  else {
    os << "null";
  }
  os << ", folder: ";
  if (obj.folder_) {
    os << PigeonInternalToString(*obj.folder_);
  }
  else {
    os << "null";
  }
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const SaveRequest& v) {
  return v.Hash();
}

// DownloadRequest

DownloadRequest::DownloadRequest(const std::string& url)
 : url_(url) {}

DownloadRequest::DownloadRequest(
  const std::string& url,
  const std::string* name,
  const EncodableMap* headers)
 : url_(url),
    name_(name ? std::optional<std::string>(*name) : std::nullopt),
    headers_(headers ? std::optional<EncodableMap>(*headers) : std::nullopt) {}

const std::string& DownloadRequest::url() const {
  return url_;
}

void DownloadRequest::set_url(std::string_view value_arg) {
  url_ = value_arg;
}


const std::string* DownloadRequest::name() const {
  return name_ ? &(*name_) : nullptr;
}

void DownloadRequest::set_name(const std::string_view* value_arg) {
  name_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void DownloadRequest::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


const EncodableMap* DownloadRequest::headers() const {
  return headers_ ? &(*headers_) : nullptr;
}

void DownloadRequest::set_headers(const EncodableMap* value_arg) {
  headers_ = value_arg ? std::optional<EncodableMap>(*value_arg) : std::nullopt;
}

void DownloadRequest::set_headers(const EncodableMap& value_arg) {
  headers_ = value_arg;
}


EncodableList DownloadRequest::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(url_));
  list.push_back(name_ ? EncodableValue(*name_) : EncodableValue());
  list.push_back(headers_ ? EncodableValue(*headers_) : EncodableValue());
  return list;
}

DownloadRequest DownloadRequest::FromEncodableList(const EncodableList& list) {
  DownloadRequest decoded(
    std::get<std::string>(list[0]));
  auto& encodable_name = list[1];
  if (!encodable_name.IsNull()) {
    decoded.set_name(std::get<std::string>(encodable_name));
  }
  auto& encodable_headers = list[2];
  if (!encodable_headers.IsNull()) {
    decoded.set_headers(std::get<EncodableMap>(encodable_headers));
  }
  return decoded;
}

bool DownloadRequest::operator==(const DownloadRequest& other) const {
  return PigeonInternalDeepEquals(url_, other.url_) && PigeonInternalDeepEquals(name_, other.name_) && PigeonInternalDeepEquals(headers_, other.headers_);
}

bool DownloadRequest::operator!=(const DownloadRequest& other) const {
  return !(*this == other);
}

size_t DownloadRequest::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(url_);
  result = result * 31 + PigeonInternalDeepHash(name_);
  result = result * 31 + PigeonInternalDeepHash(headers_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const DownloadRequest& obj) {
  os << "DownloadRequest(";
  os << "url: ";
  os << PigeonInternalToString(obj.url_);
  os << ", name: ";
  if (obj.name_) {
    os << PigeonInternalToString(*obj.name_);
  }
  else {
    os << "null";
  }
  os << ", headers: ";
  if (obj.headers_) {
    os << PigeonInternalToString(*obj.headers_);
  }
  else {
    os << "null";
  }
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const DownloadRequest& v) {
  return v.Hash();
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  ::flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        return CustomEncodableValue(SaveRequest::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 130: {
        return CustomEncodableValue(DownloadRequest::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return ::flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  ::flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(SaveRequest)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(std::any_cast<SaveRequest>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(DownloadRequest)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(std::any_cast<DownloadRequest>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  ::flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by FileSaverHostApi.
const ::flutter::StandardMessageCodec& FileSaverHostApi::GetCodec() {
  return ::flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `FileSaverHostApi` to handle messages through the `binary_messenger`.
void FileSaverHostApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  FileSaverHostApi* api) {
  FileSaverHostApi::SetUp(binary_messenger, api, "");
}

void FileSaverHostApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  FileSaverHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.file_saver.FileSaverHostApi.saveFile" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_request_arg = args.at(0);
          if (encodable_request_arg.IsNull()) {
            reply(WrapError("request_arg unexpectedly null."));
            return;
          }
          const auto& request_arg = std::any_cast<const SaveRequest&>(std::get<CustomEncodableValue>(encodable_request_arg));
          api->SaveFile(request_arg, [reply](ErrorOr<std::optional<std::string>>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            auto output_optional = std::move(output).TakeValue();
            if (output_optional) {
              wrapped.push_back(EncodableValue(std::move(output_optional).value()));
            } else {
              wrapped.push_back(EncodableValue());
            }
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.file_saver.FileSaverHostApi.saveAs" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_request_arg = args.at(0);
          if (encodable_request_arg.IsNull()) {
            reply(WrapError("request_arg unexpectedly null."));
            return;
          }
          const auto& request_arg = std::any_cast<const SaveRequest&>(std::get<CustomEncodableValue>(encodable_request_arg));
          api->SaveAs(request_arg, [reply](ErrorOr<std::optional<std::string>>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            auto output_optional = std::move(output).TakeValue();
            if (output_optional) {
              wrapped.push_back(EncodableValue(std::move(output_optional).value()));
            } else {
              wrapped.push_back(EncodableValue());
            }
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.file_saver.FileSaverHostApi.saveToGallery" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_request_arg = args.at(0);
          if (encodable_request_arg.IsNull()) {
            reply(WrapError("request_arg unexpectedly null."));
            return;
          }
          const auto& request_arg = std::any_cast<const SaveRequest&>(std::get<CustomEncodableValue>(encodable_request_arg));
          api->SaveToGallery(request_arg, [reply](ErrorOr<std::optional<std::string>>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            auto output_optional = std::move(output).TakeValue();
            if (output_optional) {
              wrapped.push_back(EncodableValue(std::move(output_optional).value()));
            } else {
              wrapped.push_back(EncodableValue());
            }
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.file_saver.FileSaverHostApi.saveToDownloads" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_request_arg = args.at(0);
          if (encodable_request_arg.IsNull()) {
            reply(WrapError("request_arg unexpectedly null."));
            return;
          }
          const auto& request_arg = std::any_cast<const SaveRequest&>(std::get<CustomEncodableValue>(encodable_request_arg));
          api->SaveToDownloads(request_arg, [reply](ErrorOr<std::optional<std::string>>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            auto output_optional = std::move(output).TakeValue();
            if (output_optional) {
              wrapped.push_back(EncodableValue(std::move(output_optional).value()));
            } else {
              wrapped.push_back(EncodableValue());
            }
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.file_saver.FileSaverHostApi.downloadLink" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_request_arg = args.at(0);
          if (encodable_request_arg.IsNull()) {
            reply(WrapError("request_arg unexpectedly null."));
            return;
          }
          const auto& request_arg = std::any_cast<const DownloadRequest&>(std::get<CustomEncodableValue>(encodable_request_arg));
          ErrorOr<std::string> output = api->DownloadLink(request_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue FileSaverHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue FileSaverHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

}  // namespace file_saver
