// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Everything a native save needs. `bytes` or `sourcePath` is set, not both.
///
/// Generated class from Pigeon that represents data sent in messages.
struct SaveRequest: Hashable, CustomStringConvertible {
  var name: String
  var bytes: FlutterStandardTypedData? = nil
  var sourcePath: String? = nil
  var fileExtension: String
  var includeExtension: Bool
  var mimeType: String
  var initialDirectory: String? = nil
  var dialogTitle: String? = nil
  /// Album for saveToGallery, subfolder for saveToDownloads.
  var folder: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SaveRequest? {
    let name = pigeonVar_list[0] as! String
    let bytes: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[1])
    let sourcePath: String? = nilOrValue(pigeonVar_list[2])
    let fileExtension = pigeonVar_list[3] as! String
    let includeExtension = pigeonVar_list[4] as! Bool
    let mimeType = pigeonVar_list[5] as! String
    let initialDirectory: String? = nilOrValue(pigeonVar_list[6])
    let dialogTitle: String? = nilOrValue(pigeonVar_list[7])
    let folder: String? = nilOrValue(pigeonVar_list[8])

    return SaveRequest(
      name: name,
      bytes: bytes,
      sourcePath: sourcePath,
      fileExtension: fileExtension,
      includeExtension: includeExtension,
      mimeType: mimeType,
      initialDirectory: initialDirectory,
      dialogTitle: dialogTitle,
      folder: folder
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      bytes,
      sourcePath,
      fileExtension,
      includeExtension,
      mimeType,
      initialDirectory,
      dialogTitle,
      folder,
    ]
  }
  static func == (lhs: SaveRequest, rhs: SaveRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.name, rhs.name) && MessagesPigeonInternal.deepEquals(lhs.bytes, rhs.bytes) && MessagesPigeonInternal.deepEquals(lhs.sourcePath, rhs.sourcePath) && MessagesPigeonInternal.deepEquals(lhs.fileExtension, rhs.fileExtension) && MessagesPigeonInternal.deepEquals(lhs.includeExtension, rhs.includeExtension) && MessagesPigeonInternal.deepEquals(lhs.mimeType, rhs.mimeType) && MessagesPigeonInternal.deepEquals(lhs.initialDirectory, rhs.initialDirectory) && MessagesPigeonInternal.deepEquals(lhs.dialogTitle, rhs.dialogTitle) && MessagesPigeonInternal.deepEquals(lhs.folder, rhs.folder)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SaveRequest")
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bytes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sourcePath, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: fileExtension, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: includeExtension, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: mimeType, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: initialDirectory, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: dialogTitle, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: folder, hasher: &hasher)
  }

  public var description: String {
    return "SaveRequest(name: \(String(describing: name)), bytes: \(String(describing: bytes)), sourcePath: \(String(describing: sourcePath)), fileExtension: \(String(describing: fileExtension)), includeExtension: \(String(describing: includeExtension)), mimeType: \(String(describing: mimeType)), initialDirectory: \(String(describing: initialDirectory)), dialogTitle: \(String(describing: dialogTitle)), folder: \(String(describing: folder)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DownloadRequest: Hashable, CustomStringConvertible {
  var url: String
  var name: String? = nil
  var headers: [String: String]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DownloadRequest? {
    let url = pigeonVar_list[0] as! String
    let name: String? = nilOrValue(pigeonVar_list[1])
    let headers: [String: String]? = nilOrValue(pigeonVar_list[2])

    return DownloadRequest(
      url: url,
      name: name,
      headers: headers
    )
  }
  func toList() -> [Any?] {
    return [
      url,
      name,
      headers,
    ]
  }
  static func == (lhs: DownloadRequest, rhs: DownloadRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.url, rhs.url) && MessagesPigeonInternal.deepEquals(lhs.name, rhs.name) && MessagesPigeonInternal.deepEquals(lhs.headers, rhs.headers)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DownloadRequest")
    MessagesPigeonInternal.deepHash(value: url, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: headers, hasher: &hasher)
  }

  public var description: String {
    return "DownloadRequest(url: \(String(describing: url)), name: \(String(describing: name)), headers: \(String(describing: headers)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return SaveRequest.fromList(self.readValue() as! [Any?])
    case 130:
      return DownloadRequest.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SaveRequest {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? DownloadRequest {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FileSaverHostApi {
  /// Writes to app storage without a dialog. Android only.
  func saveFile(request: SaveRequest) async throws -> String?
  /// Shows the platform save dialog; null when the user cancels.
  func saveAs(request: SaveRequest) async throws -> String?
  /// Adds an image or video to the photo library. Android and iOS only.
  func saveToGallery(request: SaveRequest) async throws -> String?
  /// Writes into the shared Downloads folder without a dialog. Android only;
  /// the other platforms handle it in Dart.
  func saveToDownloads(request: SaveRequest) async throws -> String?
  /// Hands a URL to the system downloader. Android only.
  func downloadLink(request: DownloadRequest) throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FileSaverHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `FileSaverHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FileSaverHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Writes to app storage without a dialog. Android only.
    let saveFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.file_saver.FileSaverHostApi.saveFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! SaveRequest
        Task { @MainActor in
          do {
            let result = try await api.saveFile(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      saveFileChannel.setMessageHandler(nil)
    }
    /// Shows the platform save dialog; null when the user cancels.
    let saveAsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.file_saver.FileSaverHostApi.saveAs\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveAsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! SaveRequest
        Task { @MainActor in
          do {
            let result = try await api.saveAs(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      saveAsChannel.setMessageHandler(nil)
    }
    /// Adds an image or video to the photo library. Android and iOS only.
    let saveToGalleryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.file_saver.FileSaverHostApi.saveToGallery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveToGalleryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! SaveRequest
        Task { @MainActor in
          do {
            let result = try await api.saveToGallery(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      saveToGalleryChannel.setMessageHandler(nil)
    }
    /// Writes into the shared Downloads folder without a dialog. Android only;
    /// the other platforms handle it in Dart.
    let saveToDownloadsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.file_saver.FileSaverHostApi.saveToDownloads\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveToDownloadsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! SaveRequest
        Task { @MainActor in
          do {
            let result = try await api.saveToDownloads(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      saveToDownloadsChannel.setMessageHandler(nil)
    }
    /// Hands a URL to the system downloader. Android only.
    let downloadLinkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.file_saver.FileSaverHostApi.downloadLink\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      downloadLinkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! DownloadRequest
        do {
          let result = try api.downloadLink(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      downloadLinkChannel.setMessageHandler(nil)
    }
  }
}
