// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Everything a native save needs. `bytes` or `sourcePath` is set, not both.
class SaveRequest {
  SaveRequest({
    required this.name,
    this.bytes,
    this.sourcePath,
    required this.fileExtension,
    required this.includeExtension,
    required this.mimeType,
    this.initialDirectory,
    this.dialogTitle,
    this.folder,
  });

  String name;

  Uint8List? bytes;

  String? sourcePath;

  String fileExtension;

  bool includeExtension;

  String mimeType;

  String? initialDirectory;

  String? dialogTitle;

  /// Album for saveToGallery, subfolder for saveToDownloads.
  String? folder;

  List<Object?> _toList() {
    return <Object?>[
      name,
      bytes,
      sourcePath,
      fileExtension,
      includeExtension,
      mimeType,
      initialDirectory,
      dialogTitle,
      folder,
    ];
  }

  Object encode() {
    return _toList();
  }

  static SaveRequest decode(Object result) {
    result as List<Object?>;
    return SaveRequest(
      name: result[0]! as String,
      bytes: result[1] as Uint8List?,
      sourcePath: result[2] as String?,
      fileExtension: result[3]! as String,
      includeExtension: result[4]! as bool,
      mimeType: result[5]! as String,
      initialDirectory: result[6] as String?,
      dialogTitle: result[7] as String?,
      folder: result[8] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SaveRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) &&
        _deepEquals(bytes, other.bytes) &&
        _deepEquals(sourcePath, other.sourcePath) &&
        _deepEquals(fileExtension, other.fileExtension) &&
        _deepEquals(includeExtension, other.includeExtension) &&
        _deepEquals(mimeType, other.mimeType) &&
        _deepEquals(initialDirectory, other.initialDirectory) &&
        _deepEquals(dialogTitle, other.dialogTitle) &&
        _deepEquals(folder, other.folder);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SaveRequest(name: $name, bytes: $bytes, sourcePath: $sourcePath, fileExtension: $fileExtension, includeExtension: $includeExtension, mimeType: $mimeType, initialDirectory: $initialDirectory, dialogTitle: $dialogTitle, folder: $folder)';
  }
}

class DownloadRequest {
  DownloadRequest({required this.url, this.name, this.headers});

  String url;

  String? name;

  Map<String, String>? headers;

  List<Object?> _toList() {
    return <Object?>[url, name, headers];
  }

  Object encode() {
    return _toList();
  }

  static DownloadRequest decode(Object result) {
    result as List<Object?>;
    return DownloadRequest(
      url: result[0]! as String,
      name: result[1] as String?,
      headers: (result[2] as Map<Object?, Object?>?)?.cast<String, String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DownloadRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(url, other.url) &&
        _deepEquals(name, other.name) &&
        _deepEquals(headers, other.headers);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DownloadRequest(url: $url, name: $name, headers: $headers)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is SaveRequest) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is DownloadRequest) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return SaveRequest.decode(readValue(buffer)!);
      case 130:
        return DownloadRequest.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class FileSaverHostApi {
  /// Constructor for [FileSaverHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FileSaverHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Writes to app storage without a dialog. Android only.
  Future<String?> saveFile(SaveRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.file_saver.FileSaverHostApi.saveFile$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  /// Shows the platform save dialog; null when the user cancels.
  Future<String?> saveAs(SaveRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.file_saver.FileSaverHostApi.saveAs$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  /// Adds an image or video to the photo library. Android and iOS only.
  Future<String?> saveToGallery(SaveRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.file_saver.FileSaverHostApi.saveToGallery$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  /// Writes into the shared Downloads folder without a dialog. Android only;
  /// the other platforms handle it in Dart.
  Future<String?> saveToDownloads(SaveRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.file_saver.FileSaverHostApi.saveToDownloads$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  /// Hands a URL to the system downloader. Android only.
  Future<String> downloadLink(DownloadRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.file_saver.FileSaverHostApi.downloadLink$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }
}
