// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

/**
 * FileSaverSaveRequest:
 *
 * Everything a native save needs. `bytes` or `sourcePath` is set, not both.
 */

G_DECLARE_FINAL_TYPE(FileSaverSaveRequest, file_saver_save_request, FILE_SAVER, SAVE_REQUEST, GObject)

/**
 * file_saver_save_request_new:
 * name: field in this object.
 * bytes: field in this object.
 * bytes_length: length of @bytes.
 * source_path: field in this object.
 * file_extension: field in this object.
 * include_extension: field in this object.
 * mime_type: field in this object.
 * initial_directory: field in this object.
 * dialog_title: field in this object.
 * folder: field in this object.
 *
 * Creates a new #SaveRequest object.
 *
 * Returns: a new #FileSaverSaveRequest
 */
FileSaverSaveRequest* file_saver_save_request_new(const gchar* name, const uint8_t* bytes, size_t bytes_length, const gchar* source_path, const gchar* file_extension, gboolean include_extension, const gchar* mime_type, const gchar* initial_directory, const gchar* dialog_title, const gchar* folder);

/**
 * file_saver_save_request_get_name
 * @object: a #FileSaverSaveRequest.
 *
 * Gets the value of the name field of @object.
 *
 * Returns: the field value.
 */
const gchar* file_saver_save_request_get_name(FileSaverSaveRequest* object);

/**
 * file_saver_save_request_get_bytes
 * @object: a #FileSaverSaveRequest.
 * @length: location to write the length of this value.
 *
 * Gets the value of the bytes field of @object.
 *
 * Returns: the field value.
 */
const uint8_t* file_saver_save_request_get_bytes(FileSaverSaveRequest* object, size_t* length);

/**
 * file_saver_save_request_get_source_path
 * @object: a #FileSaverSaveRequest.
 *
 * Gets the value of the sourcePath field of @object.
 *
 * Returns: the field value.
 */
const gchar* file_saver_save_request_get_source_path(FileSaverSaveRequest* object);

/**
 * file_saver_save_request_get_file_extension
 * @object: a #FileSaverSaveRequest.
 *
 * Gets the value of the fileExtension field of @object.
 *
 * Returns: the field value.
 */
const gchar* file_saver_save_request_get_file_extension(FileSaverSaveRequest* object);

/**
 * file_saver_save_request_get_include_extension
 * @object: a #FileSaverSaveRequest.
 *
 * Gets the value of the includeExtension field of @object.
 *
 * Returns: the field value.
 */
gboolean file_saver_save_request_get_include_extension(FileSaverSaveRequest* object);

/**
 * file_saver_save_request_get_mime_type
 * @object: a #FileSaverSaveRequest.
 *
 * Gets the value of the mimeType field of @object.
 *
 * Returns: the field value.
 */
const gchar* file_saver_save_request_get_mime_type(FileSaverSaveRequest* object);

/**
 * file_saver_save_request_get_initial_directory
 * @object: a #FileSaverSaveRequest.
 *
 * Gets the value of the initialDirectory field of @object.
 *
 * Returns: the field value.
 */
const gchar* file_saver_save_request_get_initial_directory(FileSaverSaveRequest* object);

/**
 * file_saver_save_request_get_dialog_title
 * @object: a #FileSaverSaveRequest.
 *
 * Gets the value of the dialogTitle field of @object.
 *
 * Returns: the field value.
 */
const gchar* file_saver_save_request_get_dialog_title(FileSaverSaveRequest* object);

/**
 * file_saver_save_request_get_folder
 * @object: a #FileSaverSaveRequest.
 *
 * Album for saveToGallery, subfolder for saveToDownloads.
 *
 * Returns: the field value.
 */
const gchar* file_saver_save_request_get_folder(FileSaverSaveRequest* object);

/**
 * file_saver_save_request_equals:
 * @a: a #FileSaverSaveRequest.
 * @b: another #FileSaverSaveRequest.
 *
 * Checks if two #FileSaverSaveRequest objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean file_saver_save_request_equals(FileSaverSaveRequest* a, FileSaverSaveRequest* b);

/**
 * file_saver_save_request_hash:
 * @object: a #FileSaverSaveRequest.
 *
 * Calculates a hash code for a #FileSaverSaveRequest object.
 *
 * Returns: the hash code.
 */
guint file_saver_save_request_hash(FileSaverSaveRequest* object);

/**
 * file_saver_save_request_to_string:
 * @object: a #FileSaverSaveRequest.
 *
 * Returns a string representation of a #FileSaverSaveRequest object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* file_saver_save_request_to_string(FileSaverSaveRequest* object);

/**
 * FileSaverDownloadRequest:
 *
 */

G_DECLARE_FINAL_TYPE(FileSaverDownloadRequest, file_saver_download_request, FILE_SAVER, DOWNLOAD_REQUEST, GObject)

/**
 * file_saver_download_request_new:
 * url: field in this object.
 * name: field in this object.
 * headers: field in this object.
 *
 * Creates a new #DownloadRequest object.
 *
 * Returns: a new #FileSaverDownloadRequest
 */
FileSaverDownloadRequest* file_saver_download_request_new(const gchar* url, const gchar* name, FlValue* headers);

/**
 * file_saver_download_request_get_url
 * @object: a #FileSaverDownloadRequest.
 *
 * Gets the value of the url field of @object.
 *
 * Returns: the field value.
 */
const gchar* file_saver_download_request_get_url(FileSaverDownloadRequest* object);

/**
 * file_saver_download_request_get_name
 * @object: a #FileSaverDownloadRequest.
 *
 * Gets the value of the name field of @object.
 *
 * Returns: the field value.
 */
const gchar* file_saver_download_request_get_name(FileSaverDownloadRequest* object);

/**
 * file_saver_download_request_get_headers
 * @object: a #FileSaverDownloadRequest.
 *
 * Gets the value of the headers field of @object.
 *
 * Returns: the field value.
 */
FlValue* file_saver_download_request_get_headers(FileSaverDownloadRequest* object);

/**
 * file_saver_download_request_equals:
 * @a: a #FileSaverDownloadRequest.
 * @b: another #FileSaverDownloadRequest.
 *
 * Checks if two #FileSaverDownloadRequest objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean file_saver_download_request_equals(FileSaverDownloadRequest* a, FileSaverDownloadRequest* b);

/**
 * file_saver_download_request_hash:
 * @object: a #FileSaverDownloadRequest.
 *
 * Calculates a hash code for a #FileSaverDownloadRequest object.
 *
 * Returns: the hash code.
 */
guint file_saver_download_request_hash(FileSaverDownloadRequest* object);

/**
 * file_saver_download_request_to_string:
 * @object: a #FileSaverDownloadRequest.
 *
 * Returns a string representation of a #FileSaverDownloadRequest object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* file_saver_download_request_to_string(FileSaverDownloadRequest* object);

G_DECLARE_FINAL_TYPE(FileSaverMessageCodec, file_saver_message_codec, FILE_SAVER, MESSAGE_CODEC, FlStandardMessageCodec)

/**
 * Custom type ID constants:
 *
 * Constants used to identify custom types in the codec.
 * They are used in the codec to encode and decode custom types.
 * They may be used in custom object creation functions to identify the type.
 */
extern const int file_saver_save_request_type_id;
extern const int file_saver_download_request_type_id;

G_DECLARE_FINAL_TYPE(FileSaverFileSaverHostApi, file_saver_file_saver_host_api, FILE_SAVER, FILE_SAVER_HOST_API, GObject)

G_DECLARE_FINAL_TYPE(FileSaverFileSaverHostApiResponseHandle, file_saver_file_saver_host_api_response_handle, FILE_SAVER, FILE_SAVER_HOST_API_RESPONSE_HANDLE, GObject)

G_DECLARE_FINAL_TYPE(FileSaverFileSaverHostApiDownloadLinkResponse, file_saver_file_saver_host_api_download_link_response, FILE_SAVER, FILE_SAVER_HOST_API_DOWNLOAD_LINK_RESPONSE, GObject)

/**
 * file_saver_file_saver_host_api_download_link_response_new:
 *
 * Creates a new response to FileSaverHostApi.downloadLink.
 *
 * Returns: a new #FileSaverFileSaverHostApiDownloadLinkResponse
 */
FileSaverFileSaverHostApiDownloadLinkResponse* file_saver_file_saver_host_api_download_link_response_new(const gchar* return_value);

/**
 * file_saver_file_saver_host_api_download_link_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to FileSaverHostApi.downloadLink.
 *
 * Returns: a new #FileSaverFileSaverHostApiDownloadLinkResponse
 */
FileSaverFileSaverHostApiDownloadLinkResponse* file_saver_file_saver_host_api_download_link_response_new_error(const gchar* code, const gchar* message, FlValue* details);

/**
 * FileSaverFileSaverHostApiVTable:
 *
 * Table of functions exposed by FileSaverHostApi to be implemented by the API provider.
 */
typedef struct {
  void (*save_file)(FileSaverSaveRequest* request, FileSaverFileSaverHostApiResponseHandle* response_handle, gpointer user_data);
  void (*save_as)(FileSaverSaveRequest* request, FileSaverFileSaverHostApiResponseHandle* response_handle, gpointer user_data);
  void (*save_to_gallery)(FileSaverSaveRequest* request, FileSaverFileSaverHostApiResponseHandle* response_handle, gpointer user_data);
  void (*save_to_downloads)(FileSaverSaveRequest* request, FileSaverFileSaverHostApiResponseHandle* response_handle, gpointer user_data);
  FileSaverFileSaverHostApiDownloadLinkResponse* (*download_link)(FileSaverDownloadRequest* request, gpointer user_data);
} FileSaverFileSaverHostApiVTable;

/**
 * file_saver_file_saver_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the FileSaverHostApi API.
 */
void file_saver_file_saver_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const FileSaverFileSaverHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * file_saver_file_saver_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the FileSaverHostApi API.
 */
void file_saver_file_saver_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * file_saver_file_saver_host_api_respond_save_file:
 * @response_handle: a #FileSaverFileSaverHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to FileSaverHostApi.saveFile. 
 */
void file_saver_file_saver_host_api_respond_save_file(FileSaverFileSaverHostApiResponseHandle* response_handle, const gchar* return_value);

/**
 * file_saver_file_saver_host_api_respond_error_save_file:
 * @response_handle: a #FileSaverFileSaverHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to FileSaverHostApi.saveFile. 
 */
void file_saver_file_saver_host_api_respond_error_save_file(FileSaverFileSaverHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * file_saver_file_saver_host_api_respond_save_as:
 * @response_handle: a #FileSaverFileSaverHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to FileSaverHostApi.saveAs. 
 */
void file_saver_file_saver_host_api_respond_save_as(FileSaverFileSaverHostApiResponseHandle* response_handle, const gchar* return_value);

/**
 * file_saver_file_saver_host_api_respond_error_save_as:
 * @response_handle: a #FileSaverFileSaverHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to FileSaverHostApi.saveAs. 
 */
void file_saver_file_saver_host_api_respond_error_save_as(FileSaverFileSaverHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * file_saver_file_saver_host_api_respond_save_to_gallery:
 * @response_handle: a #FileSaverFileSaverHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to FileSaverHostApi.saveToGallery. 
 */
void file_saver_file_saver_host_api_respond_save_to_gallery(FileSaverFileSaverHostApiResponseHandle* response_handle, const gchar* return_value);

/**
 * file_saver_file_saver_host_api_respond_error_save_to_gallery:
 * @response_handle: a #FileSaverFileSaverHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to FileSaverHostApi.saveToGallery. 
 */
void file_saver_file_saver_host_api_respond_error_save_to_gallery(FileSaverFileSaverHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * file_saver_file_saver_host_api_respond_save_to_downloads:
 * @response_handle: a #FileSaverFileSaverHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to FileSaverHostApi.saveToDownloads. 
 */
void file_saver_file_saver_host_api_respond_save_to_downloads(FileSaverFileSaverHostApiResponseHandle* response_handle, const gchar* return_value);

/**
 * file_saver_file_saver_host_api_respond_error_save_to_downloads:
 * @response_handle: a #FileSaverFileSaverHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to FileSaverHostApi.saveToDownloads. 
 */
void file_saver_file_saver_host_api_respond_error_save_to_downloads(FileSaverFileSaverHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

G_END_DECLS

#endif  // PIGEON_MESSAGES_G_H_
