// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#include <cmath>

#include <string.h>
#include "messages.g.h"
static guint G_GNUC_UNUSED flpigeon_hash_double(double v) {
  if (std::isnan(v)) {
    return static_cast<guint>(0x7FF80000);
  }
  if (v == 0.0) {
    v = 0.0;
  }
  union { double d; uint64_t u; } u;
  u.d = v;
  return static_cast<guint>(u.u ^ (u.u >> 32));
}
static gboolean G_GNUC_UNUSED flpigeon_equals_double(double a, double b) {
  return (a == b) || (std::isnan(a) && std::isnan(b));
}
static gboolean G_GNUC_UNUSED flpigeon_deep_equals(FlValue* a, FlValue* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (fl_value_get_type(a) != fl_value_get_type(b)) {
    return FALSE;
  }
  switch (fl_value_get_type(a)) {
    case FL_VALUE_TYPE_NULL:
      return TRUE;
    case FL_VALUE_TYPE_BOOL:
      return fl_value_get_bool(a) == fl_value_get_bool(b);
    case FL_VALUE_TYPE_INT:
      return fl_value_get_int(a) == fl_value_get_int(b);
    case FL_VALUE_TYPE_FLOAT: {
      return flpigeon_equals_double(fl_value_get_float(a), fl_value_get_float(b));
    }
    case FL_VALUE_TYPE_STRING:
      return g_strcmp0(fl_value_get_string(a), fl_value_get_string(b)) == 0;
    case FL_VALUE_TYPE_UINT8_LIST:
      return fl_value_get_length(a) == fl_value_get_length(b) &&
             memcmp(fl_value_get_uint8_list(a), fl_value_get_uint8_list(b), fl_value_get_length(a)) == 0;
    case FL_VALUE_TYPE_INT32_LIST:
      return fl_value_get_length(a) == fl_value_get_length(b) &&
             memcmp(fl_value_get_int32_list(a), fl_value_get_int32_list(b), fl_value_get_length(a) * sizeof(int32_t)) == 0;
    case FL_VALUE_TYPE_INT64_LIST:
      return fl_value_get_length(a) == fl_value_get_length(b) &&
             memcmp(fl_value_get_int64_list(a), fl_value_get_int64_list(b), fl_value_get_length(a) * sizeof(int64_t)) == 0;
    case FL_VALUE_TYPE_FLOAT_LIST: {
      size_t len = fl_value_get_length(a);
      if (len != fl_value_get_length(b)) {
        return FALSE;
      }
      const double* a_data = fl_value_get_float_list(a);
      const double* b_data = fl_value_get_float_list(b);
      for (size_t i = 0; i < len; i++) {
      if (!flpigeon_equals_double(a_data[i], b_data[i])) {
        return FALSE;
      }
    }
      return TRUE;
    }
    case FL_VALUE_TYPE_LIST: {
      size_t len = fl_value_get_length(a);
      if (len != fl_value_get_length(b)) {
        return FALSE;
      }
      for (size_t i = 0; i < len; i++) {
      if (!flpigeon_deep_equals(fl_value_get_list_value(a, i), fl_value_get_list_value(b, i))) {
        return FALSE;
      }
    }
      return TRUE;
    }
    case FL_VALUE_TYPE_MAP: {
      size_t len = fl_value_get_length(a);
      if (len != fl_value_get_length(b)) {
        return FALSE;
      }
      for (size_t i = 0; i < len; i++) {
      FlValue* key = fl_value_get_map_key(a, i);
      FlValue* val = fl_value_get_map_value(a, i);
      gboolean found = FALSE;
      for (size_t j = 0; j < len; j++) {
        FlValue* b_key = fl_value_get_map_key(b, j);
        if (flpigeon_deep_equals(key, b_key)) {
          FlValue* b_val = fl_value_get_map_value(b, j);
          if (flpigeon_deep_equals(val, b_val)) {
            found = TRUE;
            break;
          } else {
            return FALSE;
          }
        }
      }
      if (!found) {
        return FALSE;
      }
    }
      return TRUE;
    }
    default:
      return FALSE;
  }
  return FALSE;
}
static guint G_GNUC_UNUSED flpigeon_deep_hash(FlValue* value) {
  if (value == nullptr) {
    return 0;
  }
  switch (fl_value_get_type(value)) {
    case FL_VALUE_TYPE_NULL:
      return 0;
    case FL_VALUE_TYPE_BOOL:
      return fl_value_get_bool(value) ? 1231 : 1237;
    case FL_VALUE_TYPE_INT: {
      int64_t v = fl_value_get_int(value);
      return static_cast<guint>(v ^ (v >> 32));
    }
    case FL_VALUE_TYPE_FLOAT:
      return flpigeon_hash_double(fl_value_get_float(value));
    case FL_VALUE_TYPE_STRING:
      return g_str_hash(fl_value_get_string(value));
    case FL_VALUE_TYPE_UINT8_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      const uint8_t* data = fl_value_get_uint8_list(value);
      for (size_t i = 0; i < len; i++) {
        result = result * 31 + data[i];
      }
      return result;
    }
    case FL_VALUE_TYPE_INT32_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      const int32_t* data = fl_value_get_int32_list(value);
      for (size_t i = 0; i < len; i++) {
        result = result * 31 + static_cast<guint>(data[i]);
      }
      return result;
    }
    case FL_VALUE_TYPE_INT64_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      const int64_t* data = fl_value_get_int64_list(value);
      for (size_t i = 0; i < len; i++) {
        result = result * 31 + static_cast<guint>(data[i] ^ (data[i] >> 32));
      }
      return result;
    }
    case FL_VALUE_TYPE_FLOAT_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      const double* data = fl_value_get_float_list(value);
      for (size_t i = 0; i < len; i++) {
      result = result * 31 + flpigeon_hash_double(data[i]);
    }
      return result;
    }
    case FL_VALUE_TYPE_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      for (size_t i = 0; i < len; i++) {
      result = result * 31 + flpigeon_deep_hash(fl_value_get_list_value(value, i));
    }
      return result;
    }
    case FL_VALUE_TYPE_MAP: {
      guint result = 0;
      size_t len = fl_value_get_length(value);
      for (size_t i = 0; i < len; i++) {
      result += ((flpigeon_deep_hash(fl_value_get_map_key(value, i)) * 31) ^ flpigeon_deep_hash(fl_value_get_map_value(value, i)));
    }
      return result;
    }
    default:
      return static_cast<guint>(fl_value_get_type(value));
  }
  return 0;
}
static gchar* G_GNUC_UNUSED flpigeon_to_string(FlValue* value) {
  if (value == nullptr) {
    return g_strdup("null");
  }
  switch (fl_value_get_type(value)) {
    case FL_VALUE_TYPE_NULL:
      return g_strdup("null");
    case FL_VALUE_TYPE_BOOL:
      return g_strdup(fl_value_get_bool(value) ? "true" : "false");
    case FL_VALUE_TYPE_INT:
      return g_strdup_printf("%" G_GINT64_FORMAT, fl_value_get_int(value));
    case FL_VALUE_TYPE_FLOAT:
      return g_strdup_printf("%g", fl_value_get_float(value));
    case FL_VALUE_TYPE_STRING:
      return g_strdup_printf("\"%s\"", fl_value_get_string(value));
    case FL_VALUE_TYPE_UINT8_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      const uint8_t* data = fl_value_get_uint8_list(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        g_string_append_printf(str, "%d", data[i]);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_INT32_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      const int32_t* data = fl_value_get_int32_list(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        g_string_append_printf(str, "%d", data[i]);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_INT64_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      const int64_t* data = fl_value_get_int64_list(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        g_string_append_printf(str, "%" G_GINT64_FORMAT, data[i]);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_FLOAT_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      const double* data = fl_value_get_float_list(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        g_string_append_printf(str, "%g", data[i]);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        gchar* item_str = flpigeon_to_string(fl_value_get_list_value(value, i));
        g_string_append(str, item_str);
        g_free(item_str);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_MAP: {
      GString* str = g_string_new("{");
      size_t len = fl_value_get_length(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        gchar* key_str = flpigeon_to_string(fl_value_get_map_key(value, i));
        gchar* val_str = flpigeon_to_string(fl_value_get_map_value(value, i));
        g_string_append_printf(str, "%s: %s", key_str, val_str);
        g_free(key_str);
        g_free(val_str);
      }
      g_string_append(str, "}");
      return g_string_free(str, FALSE);
    }
    default:
      return g_strdup("[custom]");
  }
  return g_strdup("null");
}


struct _FileSaverSaveRequest {
  GObject parent_instance;

  gchar* name;
  uint8_t* bytes;
  size_t bytes_length;
  gchar* source_path;
  gchar* file_extension;
  gboolean include_extension;
  gchar* mime_type;
  gchar* initial_directory;
  gchar* dialog_title;
  gchar* folder;
};

G_DEFINE_TYPE(FileSaverSaveRequest, file_saver_save_request, G_TYPE_OBJECT)

static void file_saver_save_request_dispose(GObject* object) {
  FileSaverSaveRequest* self = FILE_SAVER_SAVE_REQUEST(object);
  g_clear_pointer(&self->name, g_free);
  g_clear_pointer(&self->source_path, g_free);
  g_clear_pointer(&self->file_extension, g_free);
  g_clear_pointer(&self->mime_type, g_free);
  g_clear_pointer(&self->initial_directory, g_free);
  g_clear_pointer(&self->dialog_title, g_free);
  g_clear_pointer(&self->folder, g_free);
  G_OBJECT_CLASS(file_saver_save_request_parent_class)->dispose(object);
}

static void file_saver_save_request_init(FileSaverSaveRequest* self) {
}

static void file_saver_save_request_class_init(FileSaverSaveRequestClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = file_saver_save_request_dispose;
}

FileSaverSaveRequest* file_saver_save_request_new(const gchar* name, const uint8_t* bytes, size_t bytes_length, const gchar* source_path, const gchar* file_extension, gboolean include_extension, const gchar* mime_type, const gchar* initial_directory, const gchar* dialog_title, const gchar* folder) {
  FileSaverSaveRequest* self = FILE_SAVER_SAVE_REQUEST(g_object_new(file_saver_save_request_get_type(), nullptr));
  self->name = g_strdup(name);
  if (bytes != nullptr) {
    self->bytes = static_cast<uint8_t*>(memcpy(malloc(bytes_length), bytes, bytes_length));
    self->bytes_length = bytes_length;
  }
  else {
    self->bytes = nullptr;
    self->bytes_length = 0;
  }
  if (source_path != nullptr) {
    self->source_path = g_strdup(source_path);
  }
  else {
    self->source_path = nullptr;
  }
  self->file_extension = g_strdup(file_extension);
  self->include_extension = include_extension;
  self->mime_type = g_strdup(mime_type);
  if (initial_directory != nullptr) {
    self->initial_directory = g_strdup(initial_directory);
  }
  else {
    self->initial_directory = nullptr;
  }
  if (dialog_title != nullptr) {
    self->dialog_title = g_strdup(dialog_title);
  }
  else {
    self->dialog_title = nullptr;
  }
  if (folder != nullptr) {
    self->folder = g_strdup(folder);
  }
  else {
    self->folder = nullptr;
  }
  return self;
}

const gchar* file_saver_save_request_get_name(FileSaverSaveRequest* self) {
  g_return_val_if_fail(FILE_SAVER_IS_SAVE_REQUEST(self), nullptr);
  return self->name;
}

const uint8_t* file_saver_save_request_get_bytes(FileSaverSaveRequest* self, size_t* length) {
  g_return_val_if_fail(FILE_SAVER_IS_SAVE_REQUEST(self), nullptr);
  *length = self->bytes_length;
  return self->bytes;
}

const gchar* file_saver_save_request_get_source_path(FileSaverSaveRequest* self) {
  g_return_val_if_fail(FILE_SAVER_IS_SAVE_REQUEST(self), nullptr);
  return self->source_path;
}

const gchar* file_saver_save_request_get_file_extension(FileSaverSaveRequest* self) {
  g_return_val_if_fail(FILE_SAVER_IS_SAVE_REQUEST(self), nullptr);
  return self->file_extension;
}

gboolean file_saver_save_request_get_include_extension(FileSaverSaveRequest* self) {
  g_return_val_if_fail(FILE_SAVER_IS_SAVE_REQUEST(self), FALSE);
  return self->include_extension;
}

const gchar* file_saver_save_request_get_mime_type(FileSaverSaveRequest* self) {
  g_return_val_if_fail(FILE_SAVER_IS_SAVE_REQUEST(self), nullptr);
  return self->mime_type;
}

const gchar* file_saver_save_request_get_initial_directory(FileSaverSaveRequest* self) {
  g_return_val_if_fail(FILE_SAVER_IS_SAVE_REQUEST(self), nullptr);
  return self->initial_directory;
}

const gchar* file_saver_save_request_get_dialog_title(FileSaverSaveRequest* self) {
  g_return_val_if_fail(FILE_SAVER_IS_SAVE_REQUEST(self), nullptr);
  return self->dialog_title;
}

const gchar* file_saver_save_request_get_folder(FileSaverSaveRequest* self) {
  g_return_val_if_fail(FILE_SAVER_IS_SAVE_REQUEST(self), nullptr);
  return self->folder;
}

static FlValue* file_saver_save_request_to_list(FileSaverSaveRequest* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, fl_value_new_string(self->name));
  fl_value_append_take(values, self->bytes != nullptr ? fl_value_new_uint8_list(self->bytes, self->bytes_length) : fl_value_new_null());
  fl_value_append_take(values, self->source_path != nullptr ? fl_value_new_string(self->source_path) : fl_value_new_null());
  fl_value_append_take(values, fl_value_new_string(self->file_extension));
  fl_value_append_take(values, fl_value_new_bool(self->include_extension));
  fl_value_append_take(values, fl_value_new_string(self->mime_type));
  fl_value_append_take(values, self->initial_directory != nullptr ? fl_value_new_string(self->initial_directory) : fl_value_new_null());
  fl_value_append_take(values, self->dialog_title != nullptr ? fl_value_new_string(self->dialog_title) : fl_value_new_null());
  fl_value_append_take(values, self->folder != nullptr ? fl_value_new_string(self->folder) : fl_value_new_null());
  return values;
}

static FileSaverSaveRequest* file_saver_save_request_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  const gchar* name = fl_value_get_string(value0);
  FlValue* value1 = fl_value_get_list_value(values, 1);
  const uint8_t* bytes = nullptr;
  size_t bytes_length = 0;
  if (fl_value_get_type(value1) != FL_VALUE_TYPE_NULL) {
    bytes = fl_value_get_uint8_list(value1);
    bytes_length = fl_value_get_length(value1);
  }
  FlValue* value2 = fl_value_get_list_value(values, 2);
  const gchar* source_path = nullptr;
  if (fl_value_get_type(value2) != FL_VALUE_TYPE_NULL) {
    source_path = fl_value_get_string(value2);
  }
  FlValue* value3 = fl_value_get_list_value(values, 3);
  const gchar* file_extension = fl_value_get_string(value3);
  FlValue* value4 = fl_value_get_list_value(values, 4);
  gboolean include_extension = fl_value_get_bool(value4);
  FlValue* value5 = fl_value_get_list_value(values, 5);
  const gchar* mime_type = fl_value_get_string(value5);
  FlValue* value6 = fl_value_get_list_value(values, 6);
  const gchar* initial_directory = nullptr;
  if (fl_value_get_type(value6) != FL_VALUE_TYPE_NULL) {
    initial_directory = fl_value_get_string(value6);
  }
  FlValue* value7 = fl_value_get_list_value(values, 7);
  const gchar* dialog_title = nullptr;
  if (fl_value_get_type(value7) != FL_VALUE_TYPE_NULL) {
    dialog_title = fl_value_get_string(value7);
  }
  FlValue* value8 = fl_value_get_list_value(values, 8);
  const gchar* folder = nullptr;
  if (fl_value_get_type(value8) != FL_VALUE_TYPE_NULL) {
    folder = fl_value_get_string(value8);
  }
  return file_saver_save_request_new(name, bytes, bytes_length, source_path, file_extension, include_extension, mime_type, initial_directory, dialog_title, folder);
}

gboolean file_saver_save_request_equals(FileSaverSaveRequest* a, FileSaverSaveRequest* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (g_strcmp0(a->name, b->name) != 0) {
    return FALSE;
  }
  if (a->bytes != b->bytes) {
    if (a->bytes == nullptr || b->bytes == nullptr) {
      return FALSE;
    }
    if (a->bytes_length != b->bytes_length) {
      return FALSE;
    }
    if (memcmp(a->bytes, b->bytes, a->bytes_length * sizeof(uint8_t)) != 0) {
      return FALSE;
    }
  }
  if (g_strcmp0(a->source_path, b->source_path) != 0) {
    return FALSE;
  }
  if (g_strcmp0(a->file_extension, b->file_extension) != 0) {
    return FALSE;
  }
  if (a->include_extension != b->include_extension) {
    return FALSE;
  }
  if (g_strcmp0(a->mime_type, b->mime_type) != 0) {
    return FALSE;
  }
  if (g_strcmp0(a->initial_directory, b->initial_directory) != 0) {
    return FALSE;
  }
  if (g_strcmp0(a->dialog_title, b->dialog_title) != 0) {
    return FALSE;
  }
  if (g_strcmp0(a->folder, b->folder) != 0) {
    return FALSE;
  }
  return TRUE;
}

guint file_saver_save_request_hash(FileSaverSaveRequest* self) {
  g_return_val_if_fail(FILE_SAVER_IS_SAVE_REQUEST(self), 0);
  guint result = 0;
  result = result * 31 + (self->name != nullptr ? g_str_hash(self->name) : 0);
  {
    size_t len = self->bytes_length;
    const uint8_t* data = self->bytes;
    if (data != nullptr) {
      for (size_t i = 0; i < len; i++) {
        result = result * 31 + static_cast<guint>(data[i]);
      }
    }
  }
  result = result * 31 + (self->source_path != nullptr ? g_str_hash(self->source_path) : 0);
  result = result * 31 + (self->file_extension != nullptr ? g_str_hash(self->file_extension) : 0);
  result = result * 31 + static_cast<guint>(self->include_extension);
  result = result * 31 + (self->mime_type != nullptr ? g_str_hash(self->mime_type) : 0);
  result = result * 31 + (self->initial_directory != nullptr ? g_str_hash(self->initial_directory) : 0);
  result = result * 31 + (self->dialog_title != nullptr ? g_str_hash(self->dialog_title) : 0);
  result = result * 31 + (self->folder != nullptr ? g_str_hash(self->folder) : 0);
  return result;
}

gchar* file_saver_save_request_to_string(FileSaverSaveRequest* self) {
  g_return_val_if_fail(FILE_SAVER_IS_SAVE_REQUEST(self), NULL);
  GString* str = g_string_new("SaveRequest(");
  g_string_append(str, "name: ");
  if (self->name != nullptr) {
    g_string_append_printf(str, "\"%s\"", self->name);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", bytes: ");
  if (self->bytes != nullptr) {
    g_string_append(str, "[");
    size_t len = self->bytes_length;
    const uint8_t* data = self->bytes;
    for (size_t i = 0; i < len; i++) {
      if (i > 0) {
        g_string_append(str, ", ");
      }
      g_string_append_printf(str, "%d", static_cast<int>(data[i]));
    }
    g_string_append(str, "]");
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", source_path: ");
  if (self->source_path != nullptr) {
    g_string_append_printf(str, "\"%s\"", self->source_path);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", file_extension: ");
  if (self->file_extension != nullptr) {
    g_string_append_printf(str, "\"%s\"", self->file_extension);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", include_extension: ");
  g_string_append(str, self->include_extension ? "true" : "false");
  g_string_append(str, ", mime_type: ");
  if (self->mime_type != nullptr) {
    g_string_append_printf(str, "\"%s\"", self->mime_type);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", initial_directory: ");
  if (self->initial_directory != nullptr) {
    g_string_append_printf(str, "\"%s\"", self->initial_directory);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", dialog_title: ");
  if (self->dialog_title != nullptr) {
    g_string_append_printf(str, "\"%s\"", self->dialog_title);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", folder: ");
  if (self->folder != nullptr) {
    g_string_append_printf(str, "\"%s\"", self->folder);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ")");
  return g_string_free(str, FALSE);
}

struct _FileSaverDownloadRequest {
  GObject parent_instance;

  gchar* url;
  gchar* name;
  FlValue* headers;
};

G_DEFINE_TYPE(FileSaverDownloadRequest, file_saver_download_request, G_TYPE_OBJECT)

static void file_saver_download_request_dispose(GObject* object) {
  FileSaverDownloadRequest* self = FILE_SAVER_DOWNLOAD_REQUEST(object);
  g_clear_pointer(&self->url, g_free);
  g_clear_pointer(&self->name, g_free);
  g_clear_pointer(&self->headers, fl_value_unref);
  G_OBJECT_CLASS(file_saver_download_request_parent_class)->dispose(object);
}

static void file_saver_download_request_init(FileSaverDownloadRequest* self) {
}

static void file_saver_download_request_class_init(FileSaverDownloadRequestClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = file_saver_download_request_dispose;
}

FileSaverDownloadRequest* file_saver_download_request_new(const gchar* url, const gchar* name, FlValue* headers) {
  FileSaverDownloadRequest* self = FILE_SAVER_DOWNLOAD_REQUEST(g_object_new(file_saver_download_request_get_type(), nullptr));
  self->url = g_strdup(url);
  if (name != nullptr) {
    self->name = g_strdup(name);
  }
  else {
    self->name = nullptr;
  }
  if (headers != nullptr) {
    self->headers = fl_value_ref(headers);
  }
  else {
    self->headers = nullptr;
  }
  return self;
}

const gchar* file_saver_download_request_get_url(FileSaverDownloadRequest* self) {
  g_return_val_if_fail(FILE_SAVER_IS_DOWNLOAD_REQUEST(self), nullptr);
  return self->url;
}

const gchar* file_saver_download_request_get_name(FileSaverDownloadRequest* self) {
  g_return_val_if_fail(FILE_SAVER_IS_DOWNLOAD_REQUEST(self), nullptr);
  return self->name;
}

FlValue* file_saver_download_request_get_headers(FileSaverDownloadRequest* self) {
  g_return_val_if_fail(FILE_SAVER_IS_DOWNLOAD_REQUEST(self), nullptr);
  return self->headers;
}

static FlValue* file_saver_download_request_to_list(FileSaverDownloadRequest* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, fl_value_new_string(self->url));
  fl_value_append_take(values, self->name != nullptr ? fl_value_new_string(self->name) : fl_value_new_null());
  fl_value_append_take(values, self->headers != nullptr ? fl_value_ref(self->headers) : fl_value_new_null());
  return values;
}

static FileSaverDownloadRequest* file_saver_download_request_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  const gchar* url = fl_value_get_string(value0);
  FlValue* value1 = fl_value_get_list_value(values, 1);
  const gchar* name = nullptr;
  if (fl_value_get_type(value1) != FL_VALUE_TYPE_NULL) {
    name = fl_value_get_string(value1);
  }
  FlValue* value2 = fl_value_get_list_value(values, 2);
  FlValue* headers = nullptr;
  if (fl_value_get_type(value2) != FL_VALUE_TYPE_NULL) {
    headers = value2;
  }
  return file_saver_download_request_new(url, name, headers);
}

gboolean file_saver_download_request_equals(FileSaverDownloadRequest* a, FileSaverDownloadRequest* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (g_strcmp0(a->url, b->url) != 0) {
    return FALSE;
  }
  if (g_strcmp0(a->name, b->name) != 0) {
    return FALSE;
  }
  if (!flpigeon_deep_equals(a->headers, b->headers)) {
    return FALSE;
  }
  return TRUE;
}

guint file_saver_download_request_hash(FileSaverDownloadRequest* self) {
  g_return_val_if_fail(FILE_SAVER_IS_DOWNLOAD_REQUEST(self), 0);
  guint result = 0;
  result = result * 31 + (self->url != nullptr ? g_str_hash(self->url) : 0);
  result = result * 31 + (self->name != nullptr ? g_str_hash(self->name) : 0);
  result = result * 31 + flpigeon_deep_hash(self->headers);
  return result;
}

gchar* file_saver_download_request_to_string(FileSaverDownloadRequest* self) {
  g_return_val_if_fail(FILE_SAVER_IS_DOWNLOAD_REQUEST(self), NULL);
  GString* str = g_string_new("DownloadRequest(");
  g_string_append(str, "url: ");
  if (self->url != nullptr) {
    g_string_append_printf(str, "\"%s\"", self->url);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", name: ");
  if (self->name != nullptr) {
    g_string_append_printf(str, "\"%s\"", self->name);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", headers: ");
  if (self->headers != nullptr) {
    gchar* val_str = flpigeon_to_string(self->headers);
    g_string_append(str, val_str);
    g_free(val_str);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ")");
  return g_string_free(str, FALSE);
}

struct _FileSaverMessageCodec {
  FlStandardMessageCodec parent_instance;

};

G_DEFINE_TYPE(FileSaverMessageCodec, file_saver_message_codec, fl_standard_message_codec_get_type())

const int file_saver_save_request_type_id = 129;
const int file_saver_download_request_type_id = 130;

static gboolean file_saver_message_codec_write_file_saver_save_request(FlStandardMessageCodec* codec, GByteArray* buffer, FileSaverSaveRequest* value, GError** error) {
  uint8_t type = file_saver_save_request_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = file_saver_save_request_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean file_saver_message_codec_write_file_saver_download_request(FlStandardMessageCodec* codec, GByteArray* buffer, FileSaverDownloadRequest* value, GError** error) {
  uint8_t type = file_saver_download_request_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = file_saver_download_request_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean file_saver_message_codec_write_value(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  if (fl_value_get_type(value) == FL_VALUE_TYPE_CUSTOM) {
    switch (fl_value_get_custom_type(value)) {
      case file_saver_save_request_type_id:
        return file_saver_message_codec_write_file_saver_save_request(codec, buffer, FILE_SAVER_SAVE_REQUEST(fl_value_get_custom_value_object(value)), error);
      case file_saver_download_request_type_id:
        return file_saver_message_codec_write_file_saver_download_request(codec, buffer, FILE_SAVER_DOWNLOAD_REQUEST(fl_value_get_custom_value_object(value)), error);
    }
  }

  return FL_STANDARD_MESSAGE_CODEC_CLASS(file_saver_message_codec_parent_class)->write_value(codec, buffer, value, error);
}

static FlValue* file_saver_message_codec_read_file_saver_save_request(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(FileSaverSaveRequest) value = file_saver_save_request_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(file_saver_save_request_type_id, G_OBJECT(value));
}

static FlValue* file_saver_message_codec_read_file_saver_download_request(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(FileSaverDownloadRequest) value = file_saver_download_request_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(file_saver_download_request_type_id, G_OBJECT(value));
}

static FlValue* file_saver_message_codec_read_value_of_type(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, int type, GError** error) {
  switch (type) {
    case file_saver_save_request_type_id:
      return file_saver_message_codec_read_file_saver_save_request(codec, buffer, offset, error);
    case file_saver_download_request_type_id:
      return file_saver_message_codec_read_file_saver_download_request(codec, buffer, offset, error);
    default:
      return FL_STANDARD_MESSAGE_CODEC_CLASS(file_saver_message_codec_parent_class)->read_value_of_type(codec, buffer, offset, type, error);
  }
}

static void file_saver_message_codec_init(FileSaverMessageCodec* self) {
}

static void file_saver_message_codec_class_init(FileSaverMessageCodecClass* klass) {
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->write_value = file_saver_message_codec_write_value;
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->read_value_of_type = file_saver_message_codec_read_value_of_type;
}

static FileSaverMessageCodec* file_saver_message_codec_new() {
  FileSaverMessageCodec* self = FILE_SAVER_MESSAGE_CODEC(g_object_new(file_saver_message_codec_get_type(), nullptr));
  return self;
}

struct _FileSaverFileSaverHostApiResponseHandle {
  GObject parent_instance;

  FlBasicMessageChannel* channel;
  FlBasicMessageChannelResponseHandle* response_handle;
};

G_DEFINE_TYPE(FileSaverFileSaverHostApiResponseHandle, file_saver_file_saver_host_api_response_handle, G_TYPE_OBJECT)

static void file_saver_file_saver_host_api_response_handle_dispose(GObject* object) {
  FileSaverFileSaverHostApiResponseHandle* self = FILE_SAVER_FILE_SAVER_HOST_API_RESPONSE_HANDLE(object);
  g_clear_object(&self->channel);
  g_clear_object(&self->response_handle);
  G_OBJECT_CLASS(file_saver_file_saver_host_api_response_handle_parent_class)->dispose(object);
}

static void file_saver_file_saver_host_api_response_handle_init(FileSaverFileSaverHostApiResponseHandle* self) {
}

static void file_saver_file_saver_host_api_response_handle_class_init(FileSaverFileSaverHostApiResponseHandleClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = file_saver_file_saver_host_api_response_handle_dispose;
}

static FileSaverFileSaverHostApiResponseHandle* file_saver_file_saver_host_api_response_handle_new(FlBasicMessageChannel* channel, FlBasicMessageChannelResponseHandle* response_handle) {
  FileSaverFileSaverHostApiResponseHandle* self = FILE_SAVER_FILE_SAVER_HOST_API_RESPONSE_HANDLE(g_object_new(file_saver_file_saver_host_api_response_handle_get_type(), nullptr));
  self->channel = FL_BASIC_MESSAGE_CHANNEL(g_object_ref(channel));
  self->response_handle = FL_BASIC_MESSAGE_CHANNEL_RESPONSE_HANDLE(g_object_ref(response_handle));
  return self;
}

G_DECLARE_FINAL_TYPE(FileSaverFileSaverHostApiSaveFileResponse, file_saver_file_saver_host_api_save_file_response, FILE_SAVER, FILE_SAVER_HOST_API_SAVE_FILE_RESPONSE, GObject)

struct _FileSaverFileSaverHostApiSaveFileResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(FileSaverFileSaverHostApiSaveFileResponse, file_saver_file_saver_host_api_save_file_response, G_TYPE_OBJECT)

static void file_saver_file_saver_host_api_save_file_response_dispose(GObject* object) {
  FileSaverFileSaverHostApiSaveFileResponse* self = FILE_SAVER_FILE_SAVER_HOST_API_SAVE_FILE_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(file_saver_file_saver_host_api_save_file_response_parent_class)->dispose(object);
}

static void file_saver_file_saver_host_api_save_file_response_init(FileSaverFileSaverHostApiSaveFileResponse* self) {
}

static void file_saver_file_saver_host_api_save_file_response_class_init(FileSaverFileSaverHostApiSaveFileResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = file_saver_file_saver_host_api_save_file_response_dispose;
}

static FileSaverFileSaverHostApiSaveFileResponse* file_saver_file_saver_host_api_save_file_response_new(const gchar* return_value) {
  FileSaverFileSaverHostApiSaveFileResponse* self = FILE_SAVER_FILE_SAVER_HOST_API_SAVE_FILE_RESPONSE(g_object_new(file_saver_file_saver_host_api_save_file_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, return_value != nullptr ? fl_value_new_string(return_value) : fl_value_new_null());
  return self;
}

static FileSaverFileSaverHostApiSaveFileResponse* file_saver_file_saver_host_api_save_file_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  FileSaverFileSaverHostApiSaveFileResponse* self = FILE_SAVER_FILE_SAVER_HOST_API_SAVE_FILE_RESPONSE(g_object_new(file_saver_file_saver_host_api_save_file_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

G_DECLARE_FINAL_TYPE(FileSaverFileSaverHostApiSaveAsResponse, file_saver_file_saver_host_api_save_as_response, FILE_SAVER, FILE_SAVER_HOST_API_SAVE_AS_RESPONSE, GObject)

struct _FileSaverFileSaverHostApiSaveAsResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(FileSaverFileSaverHostApiSaveAsResponse, file_saver_file_saver_host_api_save_as_response, G_TYPE_OBJECT)

static void file_saver_file_saver_host_api_save_as_response_dispose(GObject* object) {
  FileSaverFileSaverHostApiSaveAsResponse* self = FILE_SAVER_FILE_SAVER_HOST_API_SAVE_AS_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(file_saver_file_saver_host_api_save_as_response_parent_class)->dispose(object);
}

static void file_saver_file_saver_host_api_save_as_response_init(FileSaverFileSaverHostApiSaveAsResponse* self) {
}

static void file_saver_file_saver_host_api_save_as_response_class_init(FileSaverFileSaverHostApiSaveAsResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = file_saver_file_saver_host_api_save_as_response_dispose;
}

static FileSaverFileSaverHostApiSaveAsResponse* file_saver_file_saver_host_api_save_as_response_new(const gchar* return_value) {
  FileSaverFileSaverHostApiSaveAsResponse* self = FILE_SAVER_FILE_SAVER_HOST_API_SAVE_AS_RESPONSE(g_object_new(file_saver_file_saver_host_api_save_as_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, return_value != nullptr ? fl_value_new_string(return_value) : fl_value_new_null());
  return self;
}

static FileSaverFileSaverHostApiSaveAsResponse* file_saver_file_saver_host_api_save_as_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  FileSaverFileSaverHostApiSaveAsResponse* self = FILE_SAVER_FILE_SAVER_HOST_API_SAVE_AS_RESPONSE(g_object_new(file_saver_file_saver_host_api_save_as_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

G_DECLARE_FINAL_TYPE(FileSaverFileSaverHostApiSaveToGalleryResponse, file_saver_file_saver_host_api_save_to_gallery_response, FILE_SAVER, FILE_SAVER_HOST_API_SAVE_TO_GALLERY_RESPONSE, GObject)

struct _FileSaverFileSaverHostApiSaveToGalleryResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(FileSaverFileSaverHostApiSaveToGalleryResponse, file_saver_file_saver_host_api_save_to_gallery_response, G_TYPE_OBJECT)

static void file_saver_file_saver_host_api_save_to_gallery_response_dispose(GObject* object) {
  FileSaverFileSaverHostApiSaveToGalleryResponse* self = FILE_SAVER_FILE_SAVER_HOST_API_SAVE_TO_GALLERY_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(file_saver_file_saver_host_api_save_to_gallery_response_parent_class)->dispose(object);
}

static void file_saver_file_saver_host_api_save_to_gallery_response_init(FileSaverFileSaverHostApiSaveToGalleryResponse* self) {
}

static void file_saver_file_saver_host_api_save_to_gallery_response_class_init(FileSaverFileSaverHostApiSaveToGalleryResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = file_saver_file_saver_host_api_save_to_gallery_response_dispose;
}

static FileSaverFileSaverHostApiSaveToGalleryResponse* file_saver_file_saver_host_api_save_to_gallery_response_new(const gchar* return_value) {
  FileSaverFileSaverHostApiSaveToGalleryResponse* self = FILE_SAVER_FILE_SAVER_HOST_API_SAVE_TO_GALLERY_RESPONSE(g_object_new(file_saver_file_saver_host_api_save_to_gallery_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, return_value != nullptr ? fl_value_new_string(return_value) : fl_value_new_null());
  return self;
}

static FileSaverFileSaverHostApiSaveToGalleryResponse* file_saver_file_saver_host_api_save_to_gallery_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  FileSaverFileSaverHostApiSaveToGalleryResponse* self = FILE_SAVER_FILE_SAVER_HOST_API_SAVE_TO_GALLERY_RESPONSE(g_object_new(file_saver_file_saver_host_api_save_to_gallery_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

G_DECLARE_FINAL_TYPE(FileSaverFileSaverHostApiSaveToDownloadsResponse, file_saver_file_saver_host_api_save_to_downloads_response, FILE_SAVER, FILE_SAVER_HOST_API_SAVE_TO_DOWNLOADS_RESPONSE, GObject)

struct _FileSaverFileSaverHostApiSaveToDownloadsResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(FileSaverFileSaverHostApiSaveToDownloadsResponse, file_saver_file_saver_host_api_save_to_downloads_response, G_TYPE_OBJECT)

static void file_saver_file_saver_host_api_save_to_downloads_response_dispose(GObject* object) {
  FileSaverFileSaverHostApiSaveToDownloadsResponse* self = FILE_SAVER_FILE_SAVER_HOST_API_SAVE_TO_DOWNLOADS_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(file_saver_file_saver_host_api_save_to_downloads_response_parent_class)->dispose(object);
}

static void file_saver_file_saver_host_api_save_to_downloads_response_init(FileSaverFileSaverHostApiSaveToDownloadsResponse* self) {
}

static void file_saver_file_saver_host_api_save_to_downloads_response_class_init(FileSaverFileSaverHostApiSaveToDownloadsResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = file_saver_file_saver_host_api_save_to_downloads_response_dispose;
}

static FileSaverFileSaverHostApiSaveToDownloadsResponse* file_saver_file_saver_host_api_save_to_downloads_response_new(const gchar* return_value) {
  FileSaverFileSaverHostApiSaveToDownloadsResponse* self = FILE_SAVER_FILE_SAVER_HOST_API_SAVE_TO_DOWNLOADS_RESPONSE(g_object_new(file_saver_file_saver_host_api_save_to_downloads_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, return_value != nullptr ? fl_value_new_string(return_value) : fl_value_new_null());
  return self;
}

static FileSaverFileSaverHostApiSaveToDownloadsResponse* file_saver_file_saver_host_api_save_to_downloads_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  FileSaverFileSaverHostApiSaveToDownloadsResponse* self = FILE_SAVER_FILE_SAVER_HOST_API_SAVE_TO_DOWNLOADS_RESPONSE(g_object_new(file_saver_file_saver_host_api_save_to_downloads_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _FileSaverFileSaverHostApiDownloadLinkResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(FileSaverFileSaverHostApiDownloadLinkResponse, file_saver_file_saver_host_api_download_link_response, G_TYPE_OBJECT)

static void file_saver_file_saver_host_api_download_link_response_dispose(GObject* object) {
  FileSaverFileSaverHostApiDownloadLinkResponse* self = FILE_SAVER_FILE_SAVER_HOST_API_DOWNLOAD_LINK_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(file_saver_file_saver_host_api_download_link_response_parent_class)->dispose(object);
}

static void file_saver_file_saver_host_api_download_link_response_init(FileSaverFileSaverHostApiDownloadLinkResponse* self) {
}

static void file_saver_file_saver_host_api_download_link_response_class_init(FileSaverFileSaverHostApiDownloadLinkResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = file_saver_file_saver_host_api_download_link_response_dispose;
}

FileSaverFileSaverHostApiDownloadLinkResponse* file_saver_file_saver_host_api_download_link_response_new(const gchar* return_value) {
  FileSaverFileSaverHostApiDownloadLinkResponse* self = FILE_SAVER_FILE_SAVER_HOST_API_DOWNLOAD_LINK_RESPONSE(g_object_new(file_saver_file_saver_host_api_download_link_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(return_value));
  return self;
}

FileSaverFileSaverHostApiDownloadLinkResponse* file_saver_file_saver_host_api_download_link_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  FileSaverFileSaverHostApiDownloadLinkResponse* self = FILE_SAVER_FILE_SAVER_HOST_API_DOWNLOAD_LINK_RESPONSE(g_object_new(file_saver_file_saver_host_api_download_link_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _FileSaverFileSaverHostApi {
  GObject parent_instance;

  const FileSaverFileSaverHostApiVTable* vtable;
  gpointer user_data;
  GDestroyNotify user_data_free_func;
};

G_DEFINE_TYPE(FileSaverFileSaverHostApi, file_saver_file_saver_host_api, G_TYPE_OBJECT)

static void file_saver_file_saver_host_api_dispose(GObject* object) {
  FileSaverFileSaverHostApi* self = FILE_SAVER_FILE_SAVER_HOST_API(object);
  if (self->user_data != nullptr) {
    self->user_data_free_func(self->user_data);
  }
  self->user_data = nullptr;
  G_OBJECT_CLASS(file_saver_file_saver_host_api_parent_class)->dispose(object);
}

static void file_saver_file_saver_host_api_init(FileSaverFileSaverHostApi* self) {
}

static void file_saver_file_saver_host_api_class_init(FileSaverFileSaverHostApiClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = file_saver_file_saver_host_api_dispose;
}

static FileSaverFileSaverHostApi* file_saver_file_saver_host_api_new(const FileSaverFileSaverHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  FileSaverFileSaverHostApi* self = FILE_SAVER_FILE_SAVER_HOST_API(g_object_new(file_saver_file_saver_host_api_get_type(), nullptr));
  self->vtable = vtable;
  self->user_data = user_data;
  self->user_data_free_func = user_data_free_func;
  return self;
}

static void file_saver_file_saver_host_api_save_file_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  FileSaverFileSaverHostApi* self = FILE_SAVER_FILE_SAVER_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->save_file == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  FileSaverSaveRequest* request = FILE_SAVER_SAVE_REQUEST(fl_value_get_custom_value_object(value0));
  g_autoptr(FileSaverFileSaverHostApiResponseHandle) handle = file_saver_file_saver_host_api_response_handle_new(channel, response_handle);
  self->vtable->save_file(request, handle, self->user_data);
}

static void file_saver_file_saver_host_api_save_as_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  FileSaverFileSaverHostApi* self = FILE_SAVER_FILE_SAVER_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->save_as == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  FileSaverSaveRequest* request = FILE_SAVER_SAVE_REQUEST(fl_value_get_custom_value_object(value0));
  g_autoptr(FileSaverFileSaverHostApiResponseHandle) handle = file_saver_file_saver_host_api_response_handle_new(channel, response_handle);
  self->vtable->save_as(request, handle, self->user_data);
}

static void file_saver_file_saver_host_api_save_to_gallery_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  FileSaverFileSaverHostApi* self = FILE_SAVER_FILE_SAVER_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->save_to_gallery == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  FileSaverSaveRequest* request = FILE_SAVER_SAVE_REQUEST(fl_value_get_custom_value_object(value0));
  g_autoptr(FileSaverFileSaverHostApiResponseHandle) handle = file_saver_file_saver_host_api_response_handle_new(channel, response_handle);
  self->vtable->save_to_gallery(request, handle, self->user_data);
}

static void file_saver_file_saver_host_api_save_to_downloads_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  FileSaverFileSaverHostApi* self = FILE_SAVER_FILE_SAVER_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->save_to_downloads == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  FileSaverSaveRequest* request = FILE_SAVER_SAVE_REQUEST(fl_value_get_custom_value_object(value0));
  g_autoptr(FileSaverFileSaverHostApiResponseHandle) handle = file_saver_file_saver_host_api_response_handle_new(channel, response_handle);
  self->vtable->save_to_downloads(request, handle, self->user_data);
}

static void file_saver_file_saver_host_api_download_link_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  FileSaverFileSaverHostApi* self = FILE_SAVER_FILE_SAVER_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->download_link == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  FileSaverDownloadRequest* request = FILE_SAVER_DOWNLOAD_REQUEST(fl_value_get_custom_value_object(value0));
  g_autoptr(FileSaverFileSaverHostApiDownloadLinkResponse) response = self->vtable->download_link(request, self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "FileSaverHostApi", "downloadLink");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "FileSaverHostApi", "downloadLink", error->message);
  }
}

void file_saver_file_saver_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const FileSaverFileSaverHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");
  g_autoptr(FileSaverFileSaverHostApi) api_data = file_saver_file_saver_host_api_new(vtable, user_data, user_data_free_func);

  g_autoptr(FileSaverMessageCodec) codec = file_saver_message_codec_new();
  g_autofree gchar* save_file_channel_name = g_strdup_printf("dev.flutter.pigeon.file_saver.FileSaverHostApi.saveFile%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) save_file_channel = fl_basic_message_channel_new(messenger, save_file_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(save_file_channel, file_saver_file_saver_host_api_save_file_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* save_as_channel_name = g_strdup_printf("dev.flutter.pigeon.file_saver.FileSaverHostApi.saveAs%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) save_as_channel = fl_basic_message_channel_new(messenger, save_as_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(save_as_channel, file_saver_file_saver_host_api_save_as_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* save_to_gallery_channel_name = g_strdup_printf("dev.flutter.pigeon.file_saver.FileSaverHostApi.saveToGallery%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) save_to_gallery_channel = fl_basic_message_channel_new(messenger, save_to_gallery_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(save_to_gallery_channel, file_saver_file_saver_host_api_save_to_gallery_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* save_to_downloads_channel_name = g_strdup_printf("dev.flutter.pigeon.file_saver.FileSaverHostApi.saveToDownloads%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) save_to_downloads_channel = fl_basic_message_channel_new(messenger, save_to_downloads_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(save_to_downloads_channel, file_saver_file_saver_host_api_save_to_downloads_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* download_link_channel_name = g_strdup_printf("dev.flutter.pigeon.file_saver.FileSaverHostApi.downloadLink%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) download_link_channel = fl_basic_message_channel_new(messenger, download_link_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(download_link_channel, file_saver_file_saver_host_api_download_link_cb, g_object_ref(api_data), g_object_unref);
}

void file_saver_file_saver_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");

  g_autoptr(FileSaverMessageCodec) codec = file_saver_message_codec_new();
  g_autofree gchar* save_file_channel_name = g_strdup_printf("dev.flutter.pigeon.file_saver.FileSaverHostApi.saveFile%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) save_file_channel = fl_basic_message_channel_new(messenger, save_file_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(save_file_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* save_as_channel_name = g_strdup_printf("dev.flutter.pigeon.file_saver.FileSaverHostApi.saveAs%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) save_as_channel = fl_basic_message_channel_new(messenger, save_as_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(save_as_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* save_to_gallery_channel_name = g_strdup_printf("dev.flutter.pigeon.file_saver.FileSaverHostApi.saveToGallery%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) save_to_gallery_channel = fl_basic_message_channel_new(messenger, save_to_gallery_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(save_to_gallery_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* save_to_downloads_channel_name = g_strdup_printf("dev.flutter.pigeon.file_saver.FileSaverHostApi.saveToDownloads%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) save_to_downloads_channel = fl_basic_message_channel_new(messenger, save_to_downloads_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(save_to_downloads_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* download_link_channel_name = g_strdup_printf("dev.flutter.pigeon.file_saver.FileSaverHostApi.downloadLink%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) download_link_channel = fl_basic_message_channel_new(messenger, download_link_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(download_link_channel, nullptr, nullptr, nullptr);
}

void file_saver_file_saver_host_api_respond_save_file(FileSaverFileSaverHostApiResponseHandle* response_handle, const gchar* return_value) {
  g_autoptr(FileSaverFileSaverHostApiSaveFileResponse) response = file_saver_file_saver_host_api_save_file_response_new(return_value);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "FileSaverHostApi", "saveFile", error->message);
  }
}

void file_saver_file_saver_host_api_respond_error_save_file(FileSaverFileSaverHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details) {
  g_autoptr(FileSaverFileSaverHostApiSaveFileResponse) response = file_saver_file_saver_host_api_save_file_response_new_error(code, message, details);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "FileSaverHostApi", "saveFile", error->message);
  }
}

void file_saver_file_saver_host_api_respond_save_as(FileSaverFileSaverHostApiResponseHandle* response_handle, const gchar* return_value) {
  g_autoptr(FileSaverFileSaverHostApiSaveAsResponse) response = file_saver_file_saver_host_api_save_as_response_new(return_value);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "FileSaverHostApi", "saveAs", error->message);
  }
}

void file_saver_file_saver_host_api_respond_error_save_as(FileSaverFileSaverHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details) {
  g_autoptr(FileSaverFileSaverHostApiSaveAsResponse) response = file_saver_file_saver_host_api_save_as_response_new_error(code, message, details);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "FileSaverHostApi", "saveAs", error->message);
  }
}

void file_saver_file_saver_host_api_respond_save_to_gallery(FileSaverFileSaverHostApiResponseHandle* response_handle, const gchar* return_value) {
  g_autoptr(FileSaverFileSaverHostApiSaveToGalleryResponse) response = file_saver_file_saver_host_api_save_to_gallery_response_new(return_value);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "FileSaverHostApi", "saveToGallery", error->message);
  }
}

void file_saver_file_saver_host_api_respond_error_save_to_gallery(FileSaverFileSaverHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details) {
  g_autoptr(FileSaverFileSaverHostApiSaveToGalleryResponse) response = file_saver_file_saver_host_api_save_to_gallery_response_new_error(code, message, details);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "FileSaverHostApi", "saveToGallery", error->message);
  }
}

void file_saver_file_saver_host_api_respond_save_to_downloads(FileSaverFileSaverHostApiResponseHandle* response_handle, const gchar* return_value) {
  g_autoptr(FileSaverFileSaverHostApiSaveToDownloadsResponse) response = file_saver_file_saver_host_api_save_to_downloads_response_new(return_value);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "FileSaverHostApi", "saveToDownloads", error->message);
  }
}

void file_saver_file_saver_host_api_respond_error_save_to_downloads(FileSaverFileSaverHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details) {
  g_autoptr(FileSaverFileSaverHostApiSaveToDownloadsResponse) response = file_saver_file_saver_host_api_save_to_downloads_response_new_error(code, message, details);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "FileSaverHostApi", "saveToDownloads", error->message);
  }
}
